### ISSUE TITLE
Customize landmark detection

### ISSUE THREAD

**Issue by rose-jinyang** [FurkanOM/tf-blazeface#2]
Hello
how are you?
Thanks for contributing this project.
I have a question.
Is it possible to detect more 6 points for landmark even if the Blazeface architecture is changed ?
Thanks.

**Comment by FurkanOM** [comment]
Hi, thank you.
I am fine. How are you?
Yes, it is possible in theory, but I did not try.
Two simple changes will be enough to experiment.
1. When processing landmarks in data_utils, you can filter according to your requirements. For example, by deleting the **filter_landmarks** method in **dataset_generator**, you can include all the landmarks read from the file into the training pipeline.
2. By changing the total_landmarks hyperparameter in the train_utils, you can adapt the entire model structure to your requirements. You don't need to make any other changes to the model. For example, if you plan to use 68 landmarks, it will be sufficient to change this value from 6 to 68.

**Comment by rose-jinyang** [comment]
I thought so.
Thanks for your quick reply.
