### ISSUE TITLE
Training with Custom Dataset

### ISSUE THREAD

**Issue by k11-cmd** [FurkanOM/tf-blazeface#5]
Hi, how can I train the model with custom dataset ( the ground truth is in CSV Format) ?

**Comment by FurkanOM** [comment]
Hi, you can use the custom dataset by converting it to the300w_lp dataset format.

**Comment by k11-cmd** [comment]
can you please share the script to convert the custom data into 300w_lp dataset format ?

**Comment by FurkanOM** [comment]
I can't share because I didn't do it that way, you can convert your dataset by examining the300w_lp format.

**Comment by k11-cmd** [comment]
Thank You 👍
